Assets cleanups
pieces-app/cli-agent pull request #71
Opened 2024-03-25 16:03 UTC by BishoyHanyRaafat

1. change the open snippets dir to be the current dir that the user is writing the command
2. split the command_functions.py #54
3. split the list_command #66 
4. fix #56

2024-03-26 10:31 UTC, hal-8999-alpha reviewed
Code looks good overall, I ran it locally and I'm still getting index out of range. Specifically, from commands.py. I think this is a caching issue on my end (Yes I used a different env). I checked the error below and it pertains to how the code was previously written. I'm going to try to isolate all my pieces files and delete them but in the meantime it would be good to get someone else to make sure they can run it. 

AppData\Roaming\Python\Python310\site-packages\pieces\commands.py", line 142, in list_assets first_id = ids[0]

2024-03-26 11:40 UTC, BishoyHanyRaafat commented
Can u provide more details like a screenshot

2024-03-26 11:43 UTC, BishoyHanyRaafat commented
And wait there is not file called commands.py

2024-03-26 12:26 UTC, mark-at-pieces requested changes
couple things:
1. lets keep the commands how they are("list assets",...etc), but really good work splitting up the code
2. lets add/adjust the existing tests

2024-03-26 12:26 UTC, mark-at-pieces commented on src/pieces/gui.py
> +    print("  list_models     - List all registered AI models")
I would still like the commands to be "list assets" and "list apps" and "list models",

so lets move those back to how those were before but good job splitting up the code into smaller more digestible chunks.

I would also like to see the tests get updated/created for these commands to reflect the changes that you made in here.(this should also be a trend w/ each pr moving forward). IE will want a test with each feature/major adjustment to the code if there is not already one.

2024-03-26 13:24 UTC, BishoyHanyRaafat commented
@mark-at-pieces

2024-03-28 11:59 UTC, mark-at-pieces commented on src/pieces/commands/assets.py
> +        list_models()
solid

2024-03-28 12:02 UTC, mark-at-pieces approved these changes
LGTM

2024-03-28 12:05 UTC, merged